### ISSUE TITLE
Links to Vault subschemas

### ISSUE THREAD

**Issue by lena-larionova** [Kong/developer.konghq.com#347]
* Add a oneOf to the vault schema's `name` parameter in the API specs
```yaml
name:
          description: The name of the Vault that's going to be added. The Vault implementation must be installed in every Kong instance.
          type: string
          oneOf:
            - env
            - aws
            - azure
            - gcp
            - hcv
```
* Add a notOneOf (not sure about the name here) to the `prefix` parameter
```yaml
       prefix:
          description: |
            The unique prefix (or identifier) for this Vault configuration. 
            The prefix is used to load the right Vault configuration and implementation when referencing secrets with the other entities.
          type: string
          notOneOf:
            - env
            - aws
            - azure
            - gcp
            - hcv
```
* Link from the Vault `config` object entry to wherever we document the subschemas
